'use client'

import { useState, useRef, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card } from '@/components/ui/card'
import { Send, MapPin, Sparkles, User, Bot, Loader2, Download, Share } from 'lucide-react'
import { generateTravelResponse } from '@/lib/ai-service'
import { AdBanner } from '@/components/ads/ad-banner'
import { NativeAd } from '@/components/ads/native-ad'
import { GalaGPTLogoMain } from '@/components/logos/galagpt-logo-main'
import { GalaGPTLogoCompact } from '@/components/logos/galagpt-logo-compact'
import { GalaGPTLogoIcon } from '@/components/logos/galagpt-logo-icon'

interface Message {
  id: string
  type: 'user' | 'assistant'
  content: string
  timestamp: Date
}

export default function HomePage() {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [messageCount, setMessageCount] = useState(0)
  const [showUpgradePrompt, setShowUpgradePrompt] = useState(false)
  const [isClient, setIsClient] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Initialize messages on client side only to avoid hydration issues
  useEffect(() => {
    setIsClient(true)
    // Add a small delay to ensure complete hydration
    const timer = setTimeout(() => {
      setMessages([
        {
          id: '1',
          type: 'assistant',
          content: "👋 **Kumusta! I'm GalaGPT.ph, your Filipino travel assistant!**\n\nI specialize in creating personalized travel itineraries for the Philippines. I can help you with:\n\n🗺️ **Complete day-by-day itineraries**\n💰 **Budget planning & cost estimates**\n🚌 **Transportation advice**\n🍽️ **Local food recommendations**\n🏖️ **Best destinations & activities**\n💡 **Local tips & cultural insights**\n\nJust tell me where you want to go, how long you're staying, or what kind of experience you're looking for!",
          timestamp: new Date()
        }
      ])
    }, 100)

    return () => clearTimeout(timer)
  }, [])

  const formatTime = (timestamp: Date) => {
    if (!isClient) return ''
    return timestamp.toLocaleTimeString([], { 
      hour: '2-digit', 
      minute: '2-digit' 
    })
  }

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSendMessage = async () => {
    if (!input.trim() || isLoading) return

    // Check free tier limits
    if (messageCount >= 10) {
      setShowUpgradePrompt(true)
      return
    }

    const userMessage: Message = {
      id: Date.now().toString(),
      type: 'user',
      content: input,
      timestamp: new Date()
    }

    setMessages(prev => [...prev, userMessage])
    setInput('')
    setIsLoading(true)
    setMessageCount(prev => prev + 1)

    try {
      const response = await generateTravelResponse(input)
      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        type: 'assistant',
        content: response,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, assistantMessage])
    } catch (error) {
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        type: 'assistant',
        content: "I'm sorry, I encountered an error. Please try asking your question again.",
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setIsLoading(false)
    }
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSendMessage()
    }
  }

  const isItinerary = (content: string) => {
    return content.includes('Day 1') || content.includes('Day 2') || content.includes('Budget') || content.includes('₱')
  }

  const saveItinerary = (content: string) => {
    // Create a shareable text version
    const text = content.replace(/\*\*/g, '').replace(/🏝️|🏔️|🏙️|🏄|💰/g, '')
    
    // For now, just copy to clipboard - in production this could save to user account
    navigator.clipboard.writeText(`GalaGPT.ph Travel Itinerary\n\n${text}\n\nGenerated by GalaGPT.ph - Your AI Travel Assistant for the Philippines`)
    
    // You could also implement PDF download here
    alert('Itinerary copied to clipboard! You can paste it anywhere to save.')
  }

  const suggestedQuestions = [
    "Where should I go in Palawan for 5 days?",
    "How much is the budget for a Baguio weekend trip?",
    "Best places to visit in Cebu for 3 days?",
    "Island hopping in Bohol itinerary"
  ]

  const shouldShowAd = (index: number) => {
    // Show ads every 4 messages, but not in the first 2 messages
    // Only show ads if we have enough messages and it's an assistant message
    return index > 1 && (index + 1) % 4 === 0 && isClient
  }

  const getAdType = (messageContent: string) => {
    const content = messageContent.toLowerCase()
    if (content.includes('hotel') || content.includes('accommodation') || content.includes('stay')) return 'hotel'
    if (content.includes('tour') || content.includes('island') || content.includes('activity')) return 'tour'
    if (content.includes('food') || content.includes('restaurant') || content.includes('eat')) return 'restaurant'
    if (content.includes('transport') || content.includes('flight') || content.includes('bus')) return 'transport'
    return 'hotel' // default
  }

  return (
    <div className="flex h-screen bg-gray-50 pt-16">
      {!isClient ? (
        // Loading state during hydration
        <div className="flex-1 flex items-center justify-center">
          <div className="flex items-center gap-3">
            <Loader2 className="h-6 w-6 animate-spin text-purple-600" />
            <span className="text-gray-600">Loading GalaGPT.ph...</span>
          </div>
        </div>
      ) : (
        <>
          {/* Sidebar with Ads - Desktop Only */}
          <div className="hidden lg:block w-80 bg-white border-r border-gray-200 overflow-y-auto">
            <div className="sticky top-4 p-4 space-y-4">
              <div>
                <h3 className="font-semibold text-gray-900 mb-3">Travel Deals</h3>
                <div className="space-y-3">
                  <NativeAd type="hotel" />
                  <NativeAd type="tour" />
                  <NativeAd type="restaurant" />
                </div>
              </div>
              
              <AdBanner position="sidebar" />
              
              <div className="bg-purple-50 p-4 rounded-lg">
                <h4 className="font-semibold text-purple-900 mb-2">Upgrade to Premium</h4>
                <p className="text-sm text-purple-700 mb-3">
                  Get unlimited messages and ad-free experience
                </p>
                <Button size="sm" className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700">
                  Upgrade Now
                </Button>
              </div>
            </div>
          </div>

          {/* Main Chat Area */}
          <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
            {/* Header */}
            <div className="bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between flex-shrink-0">
              <div className="flex items-center gap-3 min-w-0">
                <div className="w-8 h-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg flex items-center justify-center">
                  <MapPin className="h-5 w-5 text-white" />
                </div>
                <div>
                  <h1 className="font-semibold text-gray-900">GalaGPT.ph</h1>
                  <p className="text-sm text-gray-600">AI Travel Assistant for the Philippines</p>
                </div>
              </div>
              
              {/* Message Counter for Free Users */}
              <div className="bg-purple-50 border border-purple-200 rounded-lg px-3 py-2 flex-shrink-0">
                <div className="text-sm text-purple-700 font-medium">
                  {messageCount}/10 messages used
                </div>
                <div className="text-xs text-purple-600">
                  Free tier
                </div>
              </div>
            </div>

            {/* Top Banner Ad */}
            {isClient && (
              <div className="flex-shrink-0">
                <AdBanner position="top" className="mx-4 mt-4" />
              </div>
            )}

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 min-h-0">
              {messages.map((message, index) => (
                <div key={message.id}>
                  <div className={`flex gap-3 ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}>
                    {message.type === 'assistant' && (
                      <div className="w-8 h-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full flex items-center justify-center flex-shrink-0">
                        <Bot className="h-4 w-4 text-white" />
                      </div>
                    )}
                    
                    <Card className={`max-w-2xl w-full p-3 sm:p-4 ${
                      message.type === 'user' 
                        ? 'bg-gradient-to-r from-purple-600 to-blue-600 text-white ml-4 sm:ml-12' 
                        : 'bg-white'
                    }`}>
                      <div className="whitespace-pre-wrap text-sm leading-relaxed">
                        {message.content}
                      </div>
                      <div className="flex items-center justify-between mt-3">
                        <div 
                          className={`text-xs ${
                            message.type === 'user' ? 'text-purple-100' : 'text-gray-500'
                          }`}
                          suppressHydrationWarning={true}
                        >
                          {formatTime(message.timestamp)}
                        </div>
                        
                        {/* Save Itinerary Button for Assistant Messages with Itineraries */}
                        {message.type === 'assistant' && isItinerary(message.content) && (
                          <div className="flex gap-2">
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => saveItinerary(message.content)}
                              className="text-xs h-7 px-2"
                            >
                              <Download className="h-3 w-3 mr-1" />
                              Save
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => {
                                if (navigator.share) {
                                  navigator.share({
                                    title: 'My Philippines Travel Itinerary',
                                    text: message.content.replace(/\*\*/g, ''),
                                    url: window.location.href
                                  })
                                } else {
                                  saveItinerary(message.content)
                                }
                              }}
                              className="text-xs h-7 px-2"
                            >
                              <Share className="h-3 w-3 mr-1" />
                              Share
                            </Button>
                          </div>
                        )}
                      </div>
                    </Card>

                    {message.type === 'user' && (
                      <div className="w-8 h-8 bg-gray-600 rounded-full flex items-center justify-center flex-shrink-0">
                        <User className="h-4 w-4 text-white" />
                      </div>
                    )}
                  </div>

                  {/* Show ads between messages */}
                  {shouldShowAd(index) && message.type === 'assistant' && (
                    <div className="mt-4 flex justify-center">
                      <div className="max-w-2xl w-full">
                        <AdBanner position="between-messages" />
                        <div className="mt-2 lg:hidden">
                          <NativeAd type={getAdType(message.content)} />
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              ))}

              {isLoading && (
                <div className="flex gap-3 justify-start">
                  <div className="w-8 h-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full flex items-center justify-center flex-shrink-0">
                    <Bot className="h-4 w-4 text-white" />
                  </div>
                  <Card className="max-w-2xl w-full p-3 sm:p-4 bg-white">
                    <div className="flex items-center gap-2 text-gray-600">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span className="text-sm">Thinking...</span>
                    </div>
                  </Card>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Upgrade Prompt Modal */}
            {showUpgradePrompt && (
              <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
                <Card className="max-w-md w-full p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    Daily Limit Reached
                  </h3>
                  <p className="text-gray-600 mb-4">
                    You've used all 10 free messages for today. Upgrade to Premium for unlimited conversations!
                  </p>
                  <div className="flex gap-3">
                    <Button 
                      className="flex-1 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
                      onClick={() => window.location.href = '/pricing'}
                    >
                      Upgrade to Premium
                    </Button>
                    <Button 
                      variant="outline" 
                      onClick={() => setShowUpgradePrompt(false)}
                    >
                      Maybe Later
                    </Button>
                  </div>
                </Card>
              </div>
            )}

            {/* Suggested Questions */}
            {messages.length === 1 && isClient && (
              <div className="px-4 pb-4 flex-shrink-0">
                <div className="max-w-4xl mx-auto">
                  <p className="text-sm text-gray-600 mb-3">Try asking:</p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {suggestedQuestions.map((question) => (
                      <Button
                        key={question}
                        variant="outline"
                        className="text-left justify-start h-auto p-3 text-sm"
                        onClick={() => setInput(question)}
                      >
                        <Sparkles className="h-4 w-4 mr-2 flex-shrink-0" />
                        <span className="truncate">{question}</span>
                      </Button>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Input */}
            <div className="bg-white border-t border-gray-200 p-4 flex-shrink-0">
              <div className="max-w-4xl mx-auto flex gap-3">
                <Input
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyPress={handleKeyPress}
                  placeholder={
                    messageCount >= 10 
                      ? "Upgrade to Premium for unlimited messages..." 
                      : "Ask me anything about traveling in the Philippines..."
                  }
                  className="flex-1"
                  disabled={isLoading || messageCount >= 10}
                />
                <Button 
                  onClick={handleSendMessage}
                  disabled={!input.trim() || isLoading || messageCount >= 10}
                  className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 flex-shrink-0"
                >
                  <Send className="h-4 w-4" />
                </Button>
              </div>
              <p className="text-xs text-gray-500 text-center mt-2">
                GalaGPT.ph can make mistakes. Consider checking important information.
              </p>
            </div>

            {/* Bottom Banner Ad */}
            {isClient && (
              <div className="flex-shrink-0">
                <AdBanner position="bottom" className="mx-4 mb-4" />
              </div>
            )}
          </div>
        </>
      )}
    </div>
  )
}
